[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Ge Muyang", email = "muyangge@link.cuhk.edu.hk"}]
dynamic = ["version", "description"]
