name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/tivelo
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build
      - name: Update version in pyproject.toml
        run: |
          VERSION=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//')
          echo "Setting version to $VERSION"
          sed -i "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml
          cat pyproject.toml #  To verify the version update
      - name: Commit version update
        run: |
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add pyproject.toml
            git commit -m "Update version to $VERSION"
            git push
      - name: Build package
        run: |
          python -m build       # Could also be  python setup.py sdist bdist_wheel
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1